### ISSUE TITLE
bug: Angular compile error after updated to 0.3.0

### ISSUE THREAD

**Issue by junan-trustarc** [stagewise-io/stagewise#220]
### 🔍 Debugging guide

- [x] I have read the "How to debug" guide, but the problem still persists

### Provide environment information (envinfo & npm list)

```
pnpm install
pnpm start
```

### Provide VS Code extension version

none

### Describe the bug

```
✘ [ERROR] TS2307: Cannot find module '@stagewise/extension-toolbar-srpc-contract' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/.pnpm/@stagewise+toolbar@0.3.0/node_modules/@stagewise/toolbar/dist/index.d.ts:1:30:
      1 │ ... PromptRequest } from '@stagewise/extension-toolbar-srpc-contract';
        ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

0.2.1 version was working but error after 0.3.0, any idea?
How to install "@stagewise/extension-toolbar-srpc-contract"?

### Link to reproduction

none

### To reproduce

```
pnpm install
pnpm start
```

in angular

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by junan-trustarc** [comment]
any updates??

**Comment by junan-trustarc** [comment]
JFYI, for any angular users, this is workaround to make it working (tested in 0.4.7)

```
declare module '@stagewise/extension-toolbar-srpc-contract' {
  export type PromptRequest = any;
}

declare module 'preact' {
  export type VNode<T = any> = any;
  export type ClassAttributes<T = any> = any;
  export type Component<P = any, S = any> = any;
  export type ComponentType<P = any> = any;
  export type FunctionComponent<P = any> = any;
  export type PreactDOMAttributes<T = any> = any;
}
```

**Comment by juliangoetze** [comment]
Hey @junan-trustarc, sorry for the late reply! Will have a look into this now, thanks already for the workaround!

**Comment by juliangoetze** [comment]
Unfortunately, I wasn't able to reproduce the issue... In my example angular-project, I've initialized stagewise in the `main.ts` like this:

```typescript
// main.ts
import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { App } from './app/app';
import { initToolbar } from '@stagewise/toolbar'

if (!('production' in window) || !window.production) {
  initToolbar({
    plugins: [],
  });
}


bootstrapApplication(App, appConfig)
  .catch((err) => console.error(err));
```

How did you initialize stagewise, could you share the code? @junan-trustarc

**Comment by junan-trustarc** [comment]
I just tested with new project and it worked and I realized that existing project doesn't have this "skipLibCheck" flag and getting error.


in tsconfig.json
```
"skipLibCheck": true
```

I will close ticket since this is default true on new angular version.
